config/routes.rb
RDrive::Application.routes.draw do
<<<<<<< HEAD
=======

  devise_for :users

	authenticated :user do
    root :to => "users#index"
  end

	devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :colleges

>>>>>>> 1480b8d37c03c9fd9ebe067fc35e66e4645527a1

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.role?	:admin
         can :manage, :all
#       elsif user.role? :officer
#         can :read, :all
       else
       	can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/college.rb
class College < ActiveRecord::Base
  attr_accessible :description, :name, :website, :university, :code

  serialize :contact, ActiveRecord::Coders::Hstore
  serialize :address, ActiveRecord::Coders::Hstore

  validates_presence_of :description, :name, :website, :university, :code
  validates_uniqueness_of :name, :website, :code
  validate :contact_address_validation
  validate :contact_uniqueness_validation

  has_many	:users
  has_and_belongs_to_many	:courses

  private
  def contact_address_validation
  	errors.add(:base, "Email can't be empty") if self.contact[:email].blank?
  	errors.add(:base, "Atleast provide one phone number") if self.contact[:office].blank? && self.contact[:mobile].blank?
  	errors.add(:base, "City can't be blank") if self.address[:city].blank?
  	errors.add(:base, "State can't be blank") if self.address[:state].blank?
  	errors.add(:base, "Country can't be blank") if self.address[:country].blank?
  	errors.add(:base, "Atleast provide one line address") if self.address[:line1].blank? && self.address[:line2].blank?
  	# @TODO: Pincode validation so that it takes only digits.
  	errors.add(:base, "Pincode must have exactly 6 digits") if self.address[:pincode].delete(" ").length != 6
  end

  def contact_uniqueness_validation
  	errors.add(:base, "Contact Email appears to be of someother college's") if College.where("contact -> 'email' = :contact_email", :contact_email => self.contact[:email].strip).exists?
  	errors.add(:base, "Contact Phone appears to be of someother college's") if College.where("contact -> 'office' = :contact_office", :contact_office => self.contact[:office].strip).exists? or College.where("contact -> 'mobile' = :contact_mobile", :contact_mobile => self.contact[:mobile].strip).exists?
  end

end

app/models/course.rb
class Course < ActiveRecord::Base

  attr_accessible :name

	has_and_belongs_to_many	:colleges

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name

  has_many	:users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :phone

  belongs_to	:role
  belongs_to	:college

	def role? role
		self.role == role.to_s
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController

	def new
		@college = College.new
	end

	def create
		contact = params[:college][:contact]
		address = params[:college][:address]
		args = params[:college].reject! { |k, v| k == "contact" || k == "address" }
		@college = College.new(args)
		@college.contact = { 
								:office => contact[:office],
								:mobile => contact[:mobile],
								:email => contact[:email]
							}
		@college.address = {
								:line1 => address[:line1],
								:line2 => address[:line2],
								:city => address[:city],
								:state => address[:state],
								:country => address[:country],
								:pincode => address[:pincode]
						   }
		@college.save
		render :text => @college.errors.full_messages
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!
	load_and_authorize_resource

	def index

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/colleges/new.html.erb
<% title "College Registraion" %>

<h2>College Registration</h2>


<%= form_for @college do |f| %>
	
	<div>
		<%= f.label :name, "College Name" %>
		<%= f.text_field :name, :autofocus => true %>
	</div>

	<div>
		<%= f.label :code, "College Code" %>
		<%= f.text_field :code %>
	</div>

	<div>
		<%= f.label :description, "Description" %>
		<%= f.text_area :description, :rows => "8" %>
	</div>

	<div>
		<%= f.label :university, "University" %>
		<%= f.text_field :university %>
	</div>

	<div>
		<%= f.label :website, "Website" %>
		<%= f.text_field :website %>
	</div>

	<%= f.fields_for :contact do |contact| %>
		<div>
			<%= contact.label :email, "Email" %>
			<%= contact.text_field :email %>
		</div>
		<div>
			<%= contact.label :office, "Office Phone" %>
			<%= contact.text_field :office %>
		</div>
		<div>
			<%= contact.label :mobile, "Mobile Phone" %>
			<%= contact.text_field :mobile %>
		</div>
	<% end %>

	<%= f.fields_for :address do |address| %>
		<div>
			<%= address.label :line1, "Address Line 1" %>
			<%= address.text_area :line1, :rows => "8" %>
		</div>
		<div>
			<%= address.label :line2, "Address Line 2" %>
			<%= address.text_area :line2, :rows => "8" %>
		</div>
		<div>
			<%= address.label :city %>
			<%= address.text_field :city %>
		</div>
		<div>
			<%= address.label :state %>
			<%= address.text_field :state %>
		</div>
		<div>
			<%= address.label :country %>
			<%= address.text_field :country %>
		</div>
		<div>
			<%= address.label :pincode %>
			<%= address.text_field :pincode %>
		</div>
	<% end %>

	<div>
		<%= f.submit "Submit" %>
	</div>

<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RDrive</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	<%= link_to "Home", root_path %> |
	<%= link_to "Sign Out", destroy_session_path(current_user), :method => "delete" %>
<% end -%>

<div class="row">
	<%= yield %>
</div>

</body>
</html>

app/views/users/index.html.erb
<%= title(current_user.name) %>
<%= current_user.name %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>